# Generated by Django 4.1.7 on 2023-05-21 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='messgae',
            new_name='message',
        ),
    ]
