# Generated by Django 4.1.7 on 2023-04-07 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_alter_car_features'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='tranmission',
            new_name='transmission',
        ),
    ]
